ai-cfia/fertiscan-frontend

src/Pages/JsonPage/Json.tsx

Fixed files initiation to take all files send from HomePage as a file array

Fixes #37 : File upload to backend doesnt work

---

src/App.tsx
src/Pages/FormPage/FormPage.tsx
src/Pages/HomePage/HomePage.tsx
src/main.tsx

Strict mode moved to Component root and not App root

Fix : #61 Fix react strict mode to avoid double request to backend

---

src/App.tsx
src/Model/Input-Model.tsx
src/Pages/FormPage/FormPage.tsx

Fix response to input link issue

---

src/Pages/ConfirmPage/ConfirmPage.tsx

ConfirmPage cant render (too many render requests)

---

LICENSE
public/locales/en.json
public/locales/fr.json
src/Components/Carousel/Carousel.css
src/Components/DragDropFileInput/DragDropFileInput.css
src/Components/FileList/FileList.css
src/Components/Input/Input.css
src/Components/Input/Input.tsx
src/Pages/CapturPage/CapturPage.css
src/Pages/FormPage/FormPage.css

- remove modal to expendable textarea

---

src/Components/Input/Input.tsx

change input onFocus line 132 (might come from a merge)

---

public/answer.json
src/Components/Input/Input.tsx

the issue was in list input only because ref is not textarea but div wrapper

Fix #157 : As a user, I want all textarea to be resized when the data is recieved

---

src/Components/FileList/FileList.css

width 100% on file-list

---

public/locales/en.json
public/locales/fr.json
src/Components/ContextMenu/ContextMenu.css
src/Components/ContextMenu/ContextMenu.tsx
src/Components/FileList/FileElement/FileElement.tsx
src/Components/FileList/FileList.tsx

see issue #168 
- Adding toolTip for hovering an element on fileListComponent.
- Adding delete option on context menu.
- Propagate leave event when user left the contextMenu.

Pr for issue 168

---

src/Components/ProgressBar/ProgressBar.tsx

Add tool tip on over of each progress-bar section

---

public/locales/en.json
public/locales/fr.json
src/Components/DragDropFileInput/DragDropFileInput.tsx

- Add verification of file type.
- Add new ressources for alert message related to file type.

Pr for issue #31 add restriction to image type

---

src/Pages/FormPage/FormPage.css

No issue created only a little fix

Fix carousel position

---

src/Components/DragDropFileInput/DragDropFileInput.css
src/Components/FileList/FileList.css

no issue for this one only kick fixing of home page

Fix position on home page

---

Dockerfile

ENV are setted through Vault so they should not be setted through the DockerFile

Got rid of ENV in DockerFile

---

.env.production
Dockerfile
README.md
src/Pages/FormPage/FormPage.tsx
src/Utils/stateObject.ts
vite.config.ts

+ got rid of env var in Dockerfile/ Readme
+ added env.production
+ Changed envs to be of type VITE_ rather that REACT_
+ Changed how envs are loaded in vite.config.ts

work for env vars #212

---

Dockerfile

added .env.production in dockerfile\n the .env file to be used can be…specified as an argument

copy .env.production in docker

---

.github/workflows/fertiscan-frontend-create-release.yml
.github/workflows/fertiscan-frontend-workflows.yml

Add the create build and push release workflow with the pr labeller

---

package-lock.json
package.json
src/Components/Input/Input.tsx
src/Model/Input-Model.tsx
src/Pages/FormPage/FormPage.tsx
src/Utils/deepMerge.ts
src/interfaces/Inspection.ts

issue #236: fix put inspection payload

---

README.md
docker-compose.yml

#245 
'How to' is detailed in the README. Values to update in readme can be fetched from vault under fertiscan-dev.

Issue #245: Adds compose

---

public/locales/en.json
public/locales/fr.json
src/Utils/FormCreator.ts
src/interfaces/Inspection.ts

Fix #227 by adding comments to an inspection and in the form

Fix: As an inspector, I want a “Notes/Comments” section added to the label inspection form #227

---

docker-compose.yml

Issue #253 : updates compose

---

src/Components/DragDropFileInput/DragDropFileInput.tsx

- Remove some duplicate code in the drag and drop file that was making the code more complicated for no reason.
- Modify the code so that the camera access is disable when on file mode.

Pull request for 223

---

src/app/label-data-validation/layout.tsx
src/app/label-data-validation/page.tsx
src/app/page.tsx
tailwind.config.ts

issue #308: label data validation route & page layout

---

.github/workflows/project-issue-status.yml

issue #321: project issus status workflow

---

.env.template
src/app/label-data-validation/page.tsx
src/app/layout.tsx
src/app/theme.ts
src/components/AlertBanner.tsx
src/components/DummyStepComponent.tsx
src/components/Header.tsx
src/components/ImageViewer.tsx
src/components/OrganizationsForm.tsx
src/components/__tests__/AlertBanner.test.tsx
src/stores/alertStore.ts

issue #311: improve css

---

public/locales/en/labelDataValidationPage.json
public/locales/fr/labelDataValidationPage.json
src/app/label-data-validation/__tests__/page.test.tsx
src/app/label-data-validation/page.tsx
src/components/InstructionsForm.tsx
src/components/VerifiedBilingualTable.tsx
src/components/__tests__/InstructionsForm.test.tsx
src/types/types.ts

issue #327: instructions form

---

src/app/__tests__/HomePage.test.tsx
src/app/label-data-validation/page.tsx
src/app/page.tsx
src/components/Sidenav.tsx
src/components/__tests__/Sidenav.test.tsx

Potential feature: #451 
The nextjs build failure is fixed in #447

issue #450: fix misplaced "No files uploaded" alert

---

package-lock.json
public/locales/en/confirmationPage.json
public/locales/fr/confirmationPage.json
src/app/label-data-confirmation/__tests__/ConfirmationPage.test.tsx
src/app/label-data-confirmation/page.tsx
src/stores/alertStore.ts
src/stores/fileStore.ts
src/stores/labelDataStore.ts
src/utils/client/constants.ts

issue #429: implement inspection notes
